---
title: "HW 08 Part 1"
author: "Donovan Kleinberg"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(tidyverse)
library(stringr)
install.packages("ggthemes")
library(ggthemes)
install.packages("RColorBrewer")
install.packages("viridis")
```

Chunk imports data via read_lines

```{r}

beta_gliadin <- read_lines("C:\\Misc. Files\\BI485 Folder\\Kleinberg_Donovan\\data\\beta_gliadin.txt", skip = 1)

beta_gliadin

```

Chunk removes whitespace and digits

```{r}
beta_gliadin_step_one <- beta_gliadin %>%
  str_replace_all("\\s", "\\")

beta_gliadin_step_two <- beta_gliadin_step_one %>%
  str_replace_all("\\d", "\\")

beta_gliadin_step_two
```

Chunk collapses strings

```{r}
beta_gliadin_coll <- beta_gliadin_step_two %>%
  str_c(collapse = "")

beta_gliadin_coll
```

Chunk converts to uppercase

```{r}
beta_gliadin_upper <- beta_gliadin_coll %>%
  str_to_upper()

beta_gliadin_upper

str_length(beta_gliadin_upper)
```

<<<<<<< HEAD
Chunk counts non identified nucleotides

```{r}
str_count(beta_gliadin_upper, c("A", "T", "C", "G"))

### All normal letters add up to 3310, no non-identified nucleotides are in the data set.
```

Chunk counts start and stop codons

```{r}
str_count(beta_gliadin_upper, "ATG")
str_count(beta_gliadin_upper, "TAA|TGA")
```

Chunk begins process to finding promotor

```{r}
caat_box <- "CCAAT"
tata_box <- "CTATAA"

str_count(beta_gliadin_upper, caat_box)
str_count(beta_gliadin_upper, tata_box)

```

Chunk searchs for caat_seq and tata_seq.

```{r}
caat_seq <- "CCAAT.{100,150}ATG"
str_count(beta_gliadin_upper, caat_seq)

tata_seq <- "CTATAA.{50,100}ATG"
str_count(beta_gliadin_upper, tata_seq)
```

Chunk extracts caat sequences

```{r}
caat_seqs_all <- str_extract_all(beta_gliadin_upper, caat_seq, simplify = TRUE)

str_count(caat_seqs_all)
```

Chunk finds and prints promoter region

```{r}
str_which(caat_seqs_all, tata_box)
promoter <- str_subset(caat_seqs_all, tata_box)

promoter
str_count(promoter)
```




