---
title: "HW 10 Part 1 - 3"
author: "Donovan Kleinberg"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(raster)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```

Part 1

US Maps

```{r}
usa <- map_data(map = "state") # Tidyverse or ggplot2 must be loaded

us_missouri <- map_data(map = "state", region = "missouri")

us_other <- subset(x = usa, subset = region %in% c("alabama", "florida",  "mississippi", "north carolina"))

```

```{r}
ggplot() + 
  geom_polygon(data = us_other, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "gray") +
  geom_polygon(data = us_missouri, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = "black") +
  geom_polygon(data = usa, 
               aes(x=long, 
                   y = lat, 
                   group = group), 
               fill = NA, 
               color = "black")
```

Chunk adds theme and reduces distortion

```{r}
us_map <- ggplot() + 
  geom_polygon(data = us_other, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "gray") +
  geom_polygon(data = us_missouri, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = "black") +
  geom_polygon(data = usa, 
               aes(x=long, 
                   y = lat, 
                   group = group), 
               fill = NA, 
               color = "black") +
  theme_map() +
  coord_fixed(1.3)

us_map
```

Missouri Map

```{r}
missouri <- map_data("county", "missouri")
mo_scott <- subset(missouri, subregion %in% c("scott"))

mo_map <- ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  geom_polygon(data = mo_scott, aes(x = long, y = lat, group = group), fill = "black") +
  theme_map() +
  coord_fixed(1.3)

mo_map
```

Patchwork

```{r}
us_map + mo_map + plot_layout(ncol = 2, widths = c(1.5,1))
```

My Outline Maps

USA

```{r}
mo_stlouis <- subset(missouri, subregion %in% c("st louis"))

mo_dk <- subset(missouri, subregion %in% c("dent", "knox"))

usa_dk <- ggplot() +
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), fill = NA, color = "black") +
    geom_polygon(data = us_missouri, aes(x = long, y = lat, group = group)) +
  theme_map() +
  coord_fixed(1.3)


```

Missouri

```{r}
mo_dk_final <- ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  geom_polygon(data = mo_stlouis, aes(x = long, y = lat, group = group), color = "black") +
  geom_polygon(data = mo_dk, aes(x = long, y = lat, group = group), fill = "gray") +
  theme_map() +
  coord_fixed(1.3)
```

The two combined

```{r}
usa_dk + mo_dk_final + plot_layout(ncol = 2, widths =  c(1.5, 1))
```

Part 2

Map restriction and seed

```{r}
min_long <- -126
max_long <- -104
min_lat  <-   31
max_lat  <-   50

set.seed(1979395)
```

Load bigfoot data

```{r}
bigfoot <- read.csv("C:\\Misc. Files\\BI485 Folder\\Kleinberg_Donovan\\data\\bigfoot.csv")

```

```{r}
bigfoot_ini <- filter(bigfoot,
                  long >= min_long & long <= max_long,
                  lat >= min_lat & lat <= max_lat) %>% 
  sample_n(300) %>% 
  mutate(name = "Gigantopithecus") %>% 
  dplyr::select(name, long, lat)

bigfoot_ini
```

Load bears and bind rows

```{r}
bears_base <- read.csv("C:\\Misc. Files\\BI485 Folder\\Kleinberg_Donovan\\data\\bears.csv")

both_species <- bind_rows(bigfoot_ini, bears_base)

head(both_species)

tail(both_species)
```

Map base

```{r}
base = get_stamenmap(bbox = c(min_long, 
                              min_lat, 
                              max_long, 
                              max_lat),
                     zoom = 4, 
                     maptype = "terrain-background")



ggmap(base)

base <- ggmap(base)

base + geom_point(data = bigfoot,
                  aes(x = long,
                      y = lat))
```

Adds bigfoot

```{r}
base + geom_point(data = bears_base,
                  aes(x = long,
                      y = lat))
```

Adds black bears

```{r}
base + geom_point(data = bears_base, aes(x = long, y = lat))
```

Example of both plots combined with changed seed.

```{r}
### Changed seed where it was initially entered to the last 9 digits.

base + geom_point(data = both_species,
                  aes(x = long,
                      y = lat,
                      shape = name,
                      fill = name),
                  size = 2) +
  scale_shape_manual(values = c(22:23)) +
  labs(x = "Longitude",
       y = "Latitude",
       fill = "Species",
       shape = "Species")
```

Part 3







